Repository wbond/package_control_channel, pull requests merged in 2020-02, with the labels that each got.

#7744 Add the Sqlx Builder plugin
  repository/s.json
Labels: mergeable, stale

#7739 Add codam headers package
  repository/c.json
Labels: stale

#7819 Add ST3 syntax definition for Bison
  repository/b.json
Labels: awaiting objection

#7796 Adding dotsyntax.
  repository/d.json
Labels: mergeable, stale
