Repository wbond/package_control_channel, pull requests merged in 2021-06, with the labels that each got.

#8285 Renamed package and upgrade ST version
  repository/h.json
Labels: feedback provided

#8276 Add WebAgent Syntax
  repository/w.json
Labels: feedback provided

#8288 add python-black
  repository/p.json
Labels: duplicate, feedback provided

#8289 Chromeless package: dropping linux support
  repository/c.json
Labels: feedback provided

#8253 Adding Data Wizard package
  repository/d.json
Labels: feedback provided

#8292 Fix pkg name webAgent
  repository/w.json
Labels: feedback provided

#8295 Package for Bunch.app on macOS
  repository/b.json
Labels: feedback provided

#8291 Add plugin: BootstrapAutocomplete
  repository/b.json
Labels: feedback provided

#8217 Add GNOME Devhelp package
  repository/d.json
Labels: feedback provided, stale

#8259 Add "Trusted-Coding Static Analysis" package
  repository/t.json
Labels: feedback provided, stale

#8286 ChoiceScript Syntax for Sublime 3/4
  repository/c.json
Labels: feedback provided

#8281 Add Acme color scheme & theme
  repository/a.json
Labels: feedback provided

#8298 Add 'Programatic Key Binding' plugin
  repository/p.json
Labels: feedback provided
