Repository wbond/package_control_channel, pull requests merged in 2021-03, with the labels that each got.

#8182 add AMPscript Syntax Highlighter
  repository/a.json
Labels: awaiting objection, feedback provided

#8205 Added the Auro Theme
  repository/a.json
Labels: duplicate, feedback provided

#8191 Added entries for Maya and 3ds Max Debug Adapters
  repository/d.json
Labels: feedback provided

#8208 Add Coreboot Syntax package
  repository/c.json
Labels: feedback provided

#8203 Update edge extension source repo
  repository/e.json
Labels: feedback provided

#8222 add liquidsoap package
  repository/l.json
Labels: feedback provided

#8220 add open_doi package
  repository/o.json
Labels: feedback provided

#8223 Add POVRay syntax hilight
  repository/p.json
Labels: feedback provided

#8200 Add UCFHighlighter
  repository/u.json
Labels: feedback provided

#8228 Added SmartBASIC language syntax file for SmartBASIC language.
  repository/s.json
Labels: feedback provided

#8199 Add Profile Switcher
  repository/p.json
  repository/s.json
Labels: feedback provided, takeover
