Repository wbond/package_control_channel, pull requests merged in 2021-09, with the labels that each got.

#8340 Add Exact Quick Find
  repository/e.json
Labels: feedback provided

#8344 Add "JamfLog" syntax
  repository/j.json
Labels: feedback provided

#8347 Add HDL_Automation
  repository/h.json
Labels: feedback provided

#8351 removed DeepCodeAI plugin
  repository/d.json
Labels: feedback provided, removal, stale

#8363 Added Architect language syntax
  repository/a.json
Labels: feedback provided

#8352 Add Firebase Rules Syntax
  repository/f.json
Labels: feedback provided

#8373 Transfer WolframLanguage package to WolframResearch
  repository/w.json
Labels: feedback provided, awaiting objection, takeover
