Repository wbond/package_control_channel, pull requests merged in 2022-04, with the labels that each got.

#8510 Add Butane package.
  repository/b.json
Labels: feedback provided

#8502 Add package `klog`
  repository/k.json
Labels: feedback provided

#8490 Add Moonlight Scheme
  repository/m.json
Labels: feedback provided

#8434 SphinxRefmate package added for consideration
  repository/s.json
Labels: feedback provided

#8495 Add AnyTest package
  repository/a.json
Labels: feedback provided

#8407 CodexAI
  repository/c.json
Labels: feedback provided

#8512 Add TYPO3 Fluid Snippets
  repository/t.json
Labels: feedback provided, takeover

#8506 Add Odhin Color Scheme
  repository/o.json
Labels: feedback provided

#8471 Added systemRDL
  repository/s.json
Labels: feedback provided

#8501 repository/g.json: add gcode syntax highlighting package
  repository/g.json
Labels: feedback provided

#8481 add NotePad
  repository/n.json
Labels: feedback provided, duplicate
