Repository wbond/package_control_channel, pull requests merged in 2022-12, with the labels that each got.

#8646 Remove "Material Theme"
  repository/m.json
Labels: removal

#8586 Added Quickfix List plugin
  repository/q.json
Labels: feedback provided

#8639 A syntax theme for your eyes
  repository/f.json
Labels: feedback provided

#8650 add Coddy Color Scheme
  repository/c.json
Labels: feedback provided

#8624 Add WGSL
  repository/w.json
Labels: feedback provided

#8554 Add NativeScript Core XML Syntax
  repository/n.json
Labels: feedback provided

#8627 A collection of dark Color Schemes by a professional senior Graphic and Web Designer
  repository/d.json
Labels: feedback provided, mergeable

#8644 Add Cataracted Dark
  repository/c.json
Labels: feedback provided, mergeable

#8633 Add FontSizePerView
  repository/f.json
Labels: feedback provided

#8652 Add Color Scheme - Bass
  repository/c.json
Labels: feedback provided

#8629 Added the package WordingStatus
  repository/w.json
Labels: feedback provided, takeover

#8637 rename orchid color scheme -> cattleya color scheme
  repository/c.json
  repository/o.json
Labels: feedback provided

#8643 Add Advanced Ansible Snippets
  repository/a.json
Labels: feedback provided

#8659 Change "Material Theme" author name(s)
  repository/m.json
Labels: removal

#8628 Add LionDocs Plugin
  repository/l.json
Labels: feedback provided

#8542 Add Outline Notes Publisher
  repository/o.json
Labels: feedback provided, mergeable

#8662 Add Plugin Logger
  repository/p.json
Labels: feedback provided

#8663 Add Just package
  repository/j.json
Labels: feedback provided

#8665 Add Theme Treble
  repository/t.json
Labels: feedback provided

#8621 Add CoderPad-Color-Scheme
  repository/c.json
Labels: feedback provided, mergeable

#8666 Add Rome Formatter package
  repository/r.json
Labels: feedback provided

#8657 Add OpenAI package.
  repository/o.json
Labels: feedback provided, mergeable
