Repository wbond/package_control_channel, pull requests merged in 2022-01, with the labels that each got.

#8394 Add Clojure Sublimed
  repository/c.json
Labels: feedback provided

#8375 Add clean-css
  repository/c.json
Labels: feedback provided

#8435 Add plugin Pretty Proto
  repository/p.json
Labels: feedback provided

#8422 Add plugin Paste As Column
  repository/p.json
Labels: feedback provided

#8409 Add DailyOrganizer
  repository/d.json
Labels: feedback provided, stale

#8443 YamlToJson from ryandao and Power Query syntax from Kenneth Scrubbard
  repository/y.json
Labels: feedback provided

#8452 Add SMPL Syntax plugin, syntax definition for the SMPL language
  repository/s.json
Labels: feedback provided

#8451 Merged "Xcode Build Configuration" and "Xcode Project".
  repository/x.json
Labels: feedback provided

#8457 Renamed `CodeCounter` to `CodeLines`
  repository/c.json
Labels: feedback provided

#8397 Add Comment Marks package
  repository/c.json
Labels: feedback provided

#8418 Take over Squirrel
  repository/s.json
Labels: feedback provided

#8442 Add the Hotspots package
  repository/h.json
Labels: feedback provided

#8456 Replace `Scheme` with a new repo
  repository/s.json
Labels: duplicate
