Repository wbond/package_control_channel, pull requests merged in 2023-10, with the labels that each got.

#8823 Add Compass Navigator
  repository/c.json
Labels: feedback provided, mergeable

#8827 PyRock support only for ST4
  repository/p.json
Labels: feedback provided

#8816 Diffable package added.
  repository/d.json
Labels: feedback provided, mergeable, takeover
