Repository wbond/package_control_channel, pull requests merged in 2023-09, with the labels that each got.

#8809 New Package: Reviw
  repository/r.json
Labels: feedback provided

#8818 Add Gitk and Khan
  repository/g.json
  repository/k.json
Labels: mergeable

#8819 add Prettierd Format
  repository/p.json
Labels: feedback provided, mergeable

#8817 Add FabricEngine Package
  repository/f.json
Labels: feedback provided
