Repository wbond/package_control_channel, pull requests merged in 2023-01, with the labels that each got.

#8671 Renamed Cool & Clear for better discoverability
  repository/c.json
Labels: feedback provided

#8669 Update Ruby Slim for Sublime Text 4107+
  repository/r.json
Labels: feedback provided, mergeable, takeover

#8672 added PSS DSL syntax
  repository/p.json
Labels: feedback provided

#8673 Add Switch Window plugin
  repository/s.json
Labels: mergeable

#8674 [Chef] Move chef package to tags
  repository/c.json
Labels: feedback provided

#8632 Adding AskCodi extension data
  repository/a.json
Labels: feedback provided

#8677 Add "Scarpet" package
  repository/s.json
Labels: feedback provided

#8678 Add WslBuild package
  repository/w.json
Labels: feedback provided, mergeable
