Repository wbond/package_control_channel, pull requests merged in 2023-04, with the labels that each got.

#8716 Remove Sk-ST3
  repository/s.json
Labels: removal

#8717 Add AlpineJS
  repository/a.json
Labels: feedback provided

#8700 Add Janet language support repo.
  repository/j.json
Labels: feedback provided, mergeable

#8728 Add Pluto Syntax Highlighting
  repository/p.json
Labels: feedback provided

#8705 Add Translator (multi-engine, fast) package
  repository/i.json
  repository/t.json
Labels: feedback provided, mergeable, takeover

#8727 Update Wallaby packages.json location
  channel.json
Labels: feedback provided

#8725 Add Refraction
  repository/r.json
Labels: feedback provided, mergeable

#8708 Add Pawn Kit package
  repository/p.json
Labels: feedback provided

#8730 New Package: Excel Syntax
  repository/e.json
Labels: feedback provided

#8723 add "JS Template String Converter" plugin
  repository/j.json
Labels: mergeable

#8722 Add CloseAllNoConfirm package
  repository/c.json
Labels: feedback provided
