Repository wbond/package_control_channel, pull requests merged in 2023-06, with the labels that each got.

#8755 Add NeoVintageousLineNumbers
  repository/n.json
Labels: feedback provided

#8762 Add NeoVintageousFiles
  repository/n.json
Labels: feedback provided, mergeable

#8724 New Package 'Gitignore Extended'
  repository/g.json
Labels: feedback provided

#8772 Dissolve old packages.json for "Logs Colorize"
  channel.json
  repository/l.json
Labels: mergeable

#8743 Added Alter Text plugin
  repository/a.json
Labels: feedback provided

#8778 Update EJS 2 Package
  repository/e.json
Labels: feedback provided

#8752 Adding Nano Bots Package
  repository/n.json
Labels: feedback provided, mergeable

#8779 Add Continuous Merge syntax
  repository/c.json
Labels: feedback provided

#8736 Add TimeNotify
  repository/t.json
Labels: feedback provided

#8775 Add Copy Relative Command
  repository/c.json
Labels: feedback provided
