Repository wbond/package_control_channel, pull requests merged in 2024-06, with the labels that each got.

#8919 Take over Materialize development
  repository/m.json
Labels: takeover

#8935 Add InlineOutline
  repository/i.json
Labels: feedback provided

#8936 Add Dark Castle Color Scheme
  repository/d.json
Labels: feedback provided

#8937 Blitz Search
  repository/b.json
Labels: feedback provided

#8924 Add WASM Interface Type syntax definition package
  repository/w.json
Labels: feedback provided, mergeable
