Repository wbond/package_control_channel, pull requests merged in 2024-02, with the labels that each got.

#8863 Add Yollama
  repository/y.json
Labels: feedback provided

#8877 Take-over Compare Side-By-Side
  repository/c.json
Labels: takeover

#8860 Takeover Folder Aliaser
  repository/f.json
Labels: mergeable, takeover
