Repository wbond/package_control_channel, pull requests merged in 2024-11, with the labels that each got.

#8997 Added VHS syntax package
  repository/v.json
Labels: feedback provided

#8974 Initial submission of Highlight Token.
  repository/h.json
Labels: feedback provided, mergeable

#8993 Takeover SublimeFileBrowser
  repository/f.json
Labels: mergeable, awaiting objection, takeover

#8996 Migrate PHP-Twig users to Twig
  repository/p.json
  repository/t.json
Labels: mergeable, awaiting objection, takeover

#8955 feat: add templ
  repository/t.json
Labels: feedback provided, mergeable

#8975 Initial submission of Notr.
  repository/n.json
Labels: feedback provided
