Repository wbond/package_control_channel, pull requests merged in 2024-12, with the labels that each got.

#9002 Updates p.josn, Added PLI10 syntax highlighter
  repository/p.json
Labels: feedback provided, mergeable

#9005 Add MarkdownCodeExporter
  repository/m.json
Labels: feedback provided, mergeable

#9008 Update Vue Package
  repository/v.json
Labels: mergeable, awaiting objection, takeover

#9019 Add LCOV plugin to default channel.
  repository/l.json
Labels: feedback provided

#9015 Update XSL package
  repository/x.json
Labels: mergeable, migration

#9018 Adds the Memorize package
  repository/m.json
Labels: feedback provided, mergeable
