Repository wbond/package_control_channel, pull requests merged in 2024-03, with the labels that each got.

#8864 Added AWS Helper plugin
  repository/a.json
Labels: feedback provided, mergeable

#8880 Add PIO Syntax
  repository/p.json
Labels: feedback provided

#8878 Add Explain PostgreSQL
  repository/e.json
Labels: feedback provided

#8865 Add the "evscript" package
  repository/e.json
Labels: feedback provided

#8861 Add EasyCommit
  repository/e.json
Labels: feedback provided, stale

#8895 Add comments-only color scheme
  repository/c.json
Labels: feedback provided
