Repository wbond/package_control_channel, pull requests merged in 2024-08, with the labels that each got.

#8947 Adds SSHubl
  repository/s.json
Labels: feedback provided

#8938 Add SmPL
  repository/s.json
Labels: feedback provided, stale

#8904 Rewrite of 'Add Folder To Project'.
  repository/a.json
Labels: feedback provided, mergeable

#8959 Move Helium to ST org
  repository/h.json
Labels: takeover

#8958 Add Zig Unofficial package
  repository/z.json
Labels: feedback provided

#8956 eloquence syntax
  repository/e.json
Labels: feedback provided, mergeable

#8961 Rename Better CoffeeScript to CoffeeScript
  repository/b.json
  repository/c.json
Labels: takeover
