Repository wbond/package_control_channel, pull requests merged in 2024-04, with the labels that each got.

#8894 GitHub Desktop to replace Git​Hub.app Menu
  channel.json
  repository/g.json
Labels: takeover

#8908 Added support for Carbon Syntax Highlighting
  repository/c.json
Labels: feedback provided

#8815 Rename NimLime to Nim
  repository/n.json
Labels: feedback provided, mergeable
