Repository wbond/package_control_channel, pull requests merged in 2024-07, with the labels that each got.

#8940 Add Blossom Theme
  repository/b.json
Labels: feedback provided

#8922 Add Interactivity package
  repository/i.json
Labels: feedback provided

#8948 Add Zukan Icon Theme
  repository/z.json
Labels: feedback provided, mergeable

#8945 STFileFilter v1.0.0
  repository/f.json
Labels: feedback provided

#8928 update pieces package
  repository/p.json
Labels: feedback provided, mergeable, takeover

#8949 Take over Github Tools
  repository/g.json
Labels: awaiting objection, takeover

#8951 Add Simplenote package
  repository/s.json
Labels: feedback provided
