Repository wbond/package_control_channel, pull requests merged in 2024-10, with the labels that each got.

#8979 Add Aethra Theme to Package Control
  repository/a.json
Labels: feedback provided

#8985 TokensCounter package added
  repository/t.json
Labels: feedback provided

#8992 Drop non-existing PHP Modern
  repository/p.json
Labels: removal

#8990 Migrate SCSS users to Sass
  repository/s.json
Labels: mergeable, awaiting objection
