Repository wbond/package_control_channel, pull requests merged in 2025-02, with the labels that each got.

#9039 add LiveServerPlus package
  repository/l.json
Labels: feedback provided

#9032 Add NinetyFive
  repository/n.json
Labels: feedback provided

#9028 Add TextTree syntax highlighter
  repository/t.json
Labels: feedback provided

#9049 Move Laravel Blade package to SublimeText
  channel.json
  repository/l.json
Labels: mergeable, migration

#9059 New ST4 tag series for HTML (C#)
  repository/h.json
Labels: feedback provided, mergeable

#9003 A collection of useful Sublime Text snippets for React Development
  repository/r.json
Labels: feedback provided, mergeable, awaiting objection, takeover

#9061 Fix: Correct indentation and alphabetical order for AutoTagMate entry…
  repository/a.json
Labels: feedback provided
