Repository wbond/package_control_channel, pull requests merged in 2025-08, with the labels that each got.

#9182 new fork for CoolFormat
  repository/c.json
Labels: mergeable, takeover

#9186 use community schema test action
  .github/workflows/ci.yml
  tests/__init__.py
  tests/test.py
  tests/unittest_compat.py
  utils/migrator.py
  utils/non_python_packages.py
  utils/redirect301.py
Labels: non-package

#9152 Adds RoadBookmarks plugin
  repository/r.json
Labels: feedback provided

#9157 Codexai replacement
  repository/c.json
  repository/o.json
Labels: feedback provided, mergeable
